<?xml version="1.0"?>
<robot>
<macro name="cylinder_inertia" params="m r h">
	<inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
		 iyy="${m*(3*r*r+h*h)/12}" iyz="0"
		izz="${m*r*r/2}"
  	/>
</macro>

<macro name="box_inertia" params="m x y z">
	<inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
		iyy="${m*(x*x+z*z)/12}" iyz="0"
		izz="${m*(x*x+z*z)/12}"
	/>
</macro>

<macro name="sphere_inertia" params="m r">
	<inertia  ixx="${2*m*r*r/5}" ixy="0" ixz="0"
		iyy="${2*m*r*r/5}" iyz="0"
		izz="${2*m*r*r/5}"
	/>
</macro>


<macro name="steering_wheel" params="lr tY">
<!-- steer_right -->
<link name="steer_${lr}">
    <inertial>
	<mass value="1.0" />
	<inertia ixx="1.0" ixy="0.0" ixz="0.0"
	    iyy="1.0" iyz="0.0"
	    izz="1.0" />
    </inertial>
</link>

<link name="${lr}_steering_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<gazebo reference="${lr}_steering_wheel">
  <mu1 value="1.0"/>
  <mu2 value="1.0"/>
  <kp  value="1.0" />
  <kd  value="1.0" />
  <minDepth>0.001</minDepth>
  <maxVel>0.0</maxVel>
  <fdir1 value="1 0 0"/>
  <material>Gazebo/Black</material>
</gazebo>


<joint name="${lr}_steering_wheel_hinge" type="revolute">
  <parent link="base_link"/>
  <child link="steer_${lr}"/>
<origin xyz="1 ${tY*wheelWidth/2+tY*bodyWidth/2} ${-bodyHeight / 2 + wheelRadius + bodyToFloorHeight}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="7.0" lower="${-80*PI/180}" upper="${80*PI/180}" velocity="100"/>
  <joint_properties damping="0.7" friction="0.7"/>
</joint>

<joint name="base_to_${lr}_steering_wheel" type="continuous">
    <axis xyz="0 1 0"/>
    <parent link="steer_${lr}"/>
    <child link="${lr}_steering_wheel"/>
    <!-- <origin xyz="${base_center_x+length_from_base_center_to_wheel_x} ${-reflect_right_left*length_from_base_to_wheel_y} ${radius_wheel}"/> -->
    <origin xyz="0 0 -0.16"/>
</joint>

<transmission name="${lr}_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${lr}_steering_wheel_hinge">
    <hardwareInterface>VelocityJointInterface</hardwareInterface>
  </joint>
  <actuator name="${lr}_steering_Motor">
    <hardwareInterface>VelocityJointInterface</hardwareInterface>
    <mechanicalReduction>10</mechanicalReduction>
  </actuator>
</transmission>

</macro>

<macro name="rear_wheel" params="lr tY">

<link name="${lr}_wheel">
  <collision>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <geometry>
      <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>

  <inertial>
    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
    <mass value="${wheelMass}"/>
    <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
  </inertial>
</link>

<gazebo reference="${lr}_wheel">
  <mu1 value="1.0"/>
  <mu2 value="1.0"/>
  <kp  value="1.0" />
  <kd  value="1.0" />
  <minDepth>0.001</minDepth>
  <maxVel>0.0</maxVel>
  <fdir1 value="1 0 0"/>
  <material>Gazebo/Black</material>
</gazebo>


<joint name="${lr}_wheel_hinge" type="continuous">
  <parent link="base_link"/>
  <child link="${lr}_wheel"/>
<origin xyz="${-wheelPos} ${tY*wheelWidth/2+tY*bodyWidth/2} ${-bodyHeight / 2 + wheelRadius + bodyToFloorHeight}" rpy="0 0 0" />
  <axis xyz="0 1 0" rpy="0 0 0" />
  <limit effort="300" velocity="100"/>
  <joint_properties damping="0.0" friction="0.0"/>
</joint>


<transmission name="${lr}_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${lr}_wheel_hinge">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>
  <actuator name="${lr}Motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>10</mechanicalReduction>
  </actuator>
</transmission>

</macro>
</robot>
